version: '3.5'

services:
  kafka:
    image: "bitnami/kafka:2.7.0"
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./kafka_data/:/bitnami/kafka/
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_NUM_PARTITIONS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # false
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 150MB max message size (vs 1MB default)
      - KAFKA_CFG_MESSAGE_MAX_BYTES=157286400
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=157286400
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: "bitnami/zookeeper:3.6.2"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/:/bitnami/zookeeper/

  tg_bot:
    image: tg_bot:2022-12-08
    build:
      context: ./
      dockerfile: tg_bot/Dockerfile
    depends_on:
      - kafka
      - zookeeper
